#%RAML 0.8
---
title: Projet de session
baseUri: http://localhost:3000
version: 1

/api:
  /installations:
    get:
      description: Obtenir la liste des installations pour un arrondissement.
      queryParameters:
        recherche:
          description: Une chaine de caractères qui correspond à un arrondissement.
          type: string
          required: true
      responses:
        200:
          description: La liste des installations a été correctement envoyée.
          body:
            application/json:
              schema: N/A
        500:
          description: Une erreur interne s'est produite. Consulté les logs pour plus d'informations.
    /simple:
      get:
        description: Obtenir l'information disponible pour une installation.
        queryParameters:
          recherche:
            description: Une chaine de caractères qui correspond au nom d'une installation.
            type: string
            required: true
        responses:
          200:
            description: L'information de l'installation a été correctement envoyée.
            body:
              application/json:
                schema: N/A
          500:
            description: Une erreur interne s'est produite. Consulté les logs pour plus d'informations.
